START TRANSACTION;
ALTER TABLE "Profesor" DROP COLUMN "UsuarioLogin";

ALTER TABLE "Notificacion" DROP COLUMN "DestinatarioLogin";

ALTER TABLE "Inscripcion" DROP COLUMN "Periodo";

ALTER TABLE "Estudiante" DROP COLUMN "Carrera";

ALTER TABLE "Estudiante" DROP COLUMN "CodCarrera";

ALTER TABLE "Estudiante" DROP COLUMN "UsuarioLogin";

ALTER TABLE "Asignatura" RENAME COLUMN "Semestre" TO "SemestreId";

ALTER TABLE "Usuario" ADD "Activo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Profesor" ADD "Activo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Profesor" ADD "UsuarioId" integer;

ALTER TABLE "Notificacion" ADD "UsuarioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Mensaje" ADD "ReceptorUsuarioId" integer;

ALTER TABLE "Mensaje" ADD "Seccion" text;

ALTER TABLE "Mensaje" ADD "TipoChat" text NOT NULL DEFAULT '';

ALTER TABLE "Mensaje" ADD "UsuarioId" integer NOT NULL DEFAULT 0;

ALTER TABLE "Inscripcion" ADD "PeriodoId" integer;

ALTER TABLE "Estudiante" ADD "Activo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Estudiante" ADD "CarreraId" integer;

ALTER TABLE "Estudiante" ADD "EstadoArancel" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Estudiante" ADD "UsuarioId" integer;

ALTER TABLE "ControlAcceso" ADD "UsuarioId" integer;

ALTER TABLE "Asignatura" ADD "Activo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Asignatura" ADD "CarreraId" integer;

ALTER TABLE "Anuncio" ADD "Activo" boolean NOT NULL DEFAULT FALSE;

ALTER TABLE "Anuncio" ADD "CarreraId" integer;

ALTER TABLE "Anuncio" ADD "Prioridad" text NOT NULL DEFAULT '';

ALTER TABLE "Anuncio" ADD "RolId" integer;

ALTER TABLE "Anuncio" ADD "UsuarioId" integer;

CREATE TABLE "ArancelValidacion" (
    "IdValidacion" integer GENERATED BY DEFAULT AS IDENTITY,
    "CedulaEstudiante" text NOT NULL,
    "NumeroFactura" text NOT NULL,
    "FechaValidacion" timestamp with time zone NOT NULL,
    "SecretariaId" integer,
    "MetodoPago" text NOT NULL,
    CONSTRAINT "PK_ArancelValidacion" PRIMARY KEY ("IdValidacion"),
    CONSTRAINT "FK_ArancelValidacion_Usuario_SecretariaId" FOREIGN KEY ("SecretariaId") REFERENCES "Usuario" ("IdUsuario")
);

CREATE TABLE "AuditLog" (
    "IdAudit" integer GENERATED BY DEFAULT AS IDENTITY,
    "UsuarioId" integer,
    "Accion" text NOT NULL,
    "Ruta" text NOT NULL,
    "IP" text NOT NULL,
    "Fecha" timestamp with time zone NOT NULL,
    "Detalles" text,
    "MotivoJustificado" text,
    CONSTRAINT "PK_AuditLog" PRIMARY KEY ("IdAudit"),
    CONSTRAINT "FK_AuditLog_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario")
);

CREATE TABLE "Aula" (
    "IdAula" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" text NOT NULL,
    "Edificio" text NOT NULL,
    "Piso" text NOT NULL,
    "Estado" text NOT NULL,
    "HoraApertura" timestamp with time zone,
    "ProfesorActualId" integer,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_Aula" PRIMARY KEY ("IdAula"),
    CONSTRAINT "FK_Aula_Profesor_ProfesorActualId" FOREIGN KEY ("ProfesorActualId") REFERENCES "Profesor" ("IdProfesor")
);

CREATE TABLE "EvaluacionConfig" (
    "IdEvaluacion" integer GENERATED BY DEFAULT AS IDENTITY,
    "AsignaturaId" integer NOT NULL,
    "Nombre" text NOT NULL,
    "Ponderacion" numeric NOT NULL,
    "FechaEvaluacion" timestamp with time zone NOT NULL,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_EvaluacionConfig" PRIMARY KEY ("IdEvaluacion"),
    CONSTRAINT "FK_EvaluacionConfig_Asignatura_AsignaturaId" FOREIGN KEY ("AsignaturaId") REFERENCES "Asignatura" ("IdAsignatura") ON DELETE CASCADE
);

CREATE TABLE "PinAsistencia" (
    "IdPin" integer GENERATED BY DEFAULT AS IDENTITY,
    "Pin" text NOT NULL,
    "FechaExpiracion" timestamp with time zone NOT NULL,
    "CoordinadorId" integer,
    "Activo" boolean NOT NULL,
    CONSTRAINT "PK_PinAsistencia" PRIMARY KEY ("IdPin")
);

CREATE TABLE "SolicitudApertura" (
    "IdSolicitud" integer GENERATED BY DEFAULT AS IDENTITY,
    "AulaId" integer NOT NULL,
    "ProfesorId" integer NOT NULL,
    "PersonalSeguridadId" integer,
    "FechaSolicitud" timestamp with time zone NOT NULL,
    "FechaAtencion" timestamp with time zone,
    "FechaCompletada" timestamp with time zone,
    "Estado" text NOT NULL,
    "Motivo" text,
    CONSTRAINT "PK_SolicitudApertura" PRIMARY KEY ("IdSolicitud"),
    CONSTRAINT "FK_SolicitudApertura_Aula_AulaId" FOREIGN KEY ("AulaId") REFERENCES "Aula" ("IdAula") ON DELETE CASCADE,
    CONSTRAINT "FK_SolicitudApertura_Profesor_ProfesorId" FOREIGN KEY ("ProfesorId") REFERENCES "Profesor" ("IdProfesor") ON DELETE CASCADE,
    CONSTRAINT "FK_SolicitudApertura_Usuario_PersonalSeguridadId" FOREIGN KEY ("PersonalSeguridadId") REFERENCES "Usuario" ("IdUsuario") ON DELETE RESTRICT
);

CREATE INDEX "IX_Profesor_UsuarioId" ON "Profesor" ("UsuarioId");

CREATE INDEX "IX_Notificacion_UsuarioId" ON "Notificacion" ("UsuarioId");

CREATE INDEX "IX_Mensaje_AsignaturaId" ON "Mensaje" ("AsignaturaId");

CREATE INDEX "IX_Mensaje_ReceptorUsuarioId" ON "Mensaje" ("ReceptorUsuarioId");

CREATE INDEX "IX_Mensaje_UsuarioId" ON "Mensaje" ("UsuarioId");

CREATE INDEX "IX_Inscripcion_PeriodoId" ON "Inscripcion" ("PeriodoId");

CREATE INDEX "IX_Estudiante_CarreraId" ON "Estudiante" ("CarreraId");

CREATE UNIQUE INDEX "IX_Estudiante_Cedula" ON "Estudiante" ("Cedula");

CREATE INDEX "IX_Estudiante_UsuarioId" ON "Estudiante" ("UsuarioId");

CREATE INDEX "IX_ControlAcceso_PersonalSeguridadId" ON "ControlAcceso" ("PersonalSeguridadId");

CREATE INDEX "IX_ControlAcceso_UsuarioId" ON "ControlAcceso" ("UsuarioId");

CREATE INDEX "IX_Asignatura_CarreraId" ON "Asignatura" ("CarreraId");

CREATE INDEX "IX_Asignatura_SemestreId" ON "Asignatura" ("SemestreId");

CREATE INDEX "IX_Anuncio_CarreraId" ON "Anuncio" ("CarreraId");

CREATE INDEX "IX_Anuncio_RolId" ON "Anuncio" ("RolId");

CREATE INDEX "IX_Anuncio_UsuarioId" ON "Anuncio" ("UsuarioId");

CREATE INDEX "IX_ArancelValidacion_SecretariaId" ON "ArancelValidacion" ("SecretariaId");

CREATE INDEX "IX_AuditLog_UsuarioId" ON "AuditLog" ("UsuarioId");

CREATE INDEX "IX_Aula_ProfesorActualId" ON "Aula" ("ProfesorActualId");

CREATE INDEX "IX_EvaluacionConfig_AsignaturaId" ON "EvaluacionConfig" ("AsignaturaId");

CREATE INDEX "IX_SolicitudApertura_AulaId" ON "SolicitudApertura" ("AulaId");

CREATE INDEX "IX_SolicitudApertura_PersonalSeguridadId" ON "SolicitudApertura" ("PersonalSeguridadId");

CREATE INDEX "IX_SolicitudApertura_ProfesorId" ON "SolicitudApertura" ("ProfesorId");

ALTER TABLE "Anuncio" ADD CONSTRAINT "FK_Anuncio_Carrera_CarreraId" FOREIGN KEY ("CarreraId") REFERENCES "Carrera" ("IdCarrera");

ALTER TABLE "Anuncio" ADD CONSTRAINT "FK_Anuncio_Rol_RolId" FOREIGN KEY ("RolId") REFERENCES "Rol" ("IdRol");

ALTER TABLE "Anuncio" ADD CONSTRAINT "FK_Anuncio_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario") ON DELETE RESTRICT;

ALTER TABLE "Asignatura" ADD CONSTRAINT "FK_Asignatura_Carrera_CarreraId" FOREIGN KEY ("CarreraId") REFERENCES "Carrera" ("IdCarrera");

ALTER TABLE "Asignatura" ADD CONSTRAINT "FK_Asignatura_Semestre_SemestreId" FOREIGN KEY ("SemestreId") REFERENCES "Semestre" ("IdSemestre");

ALTER TABLE "ControlAcceso" ADD CONSTRAINT "FK_ControlAcceso_Usuario_PersonalSeguridadId" FOREIGN KEY ("PersonalSeguridadId") REFERENCES "Usuario" ("IdUsuario") ON DELETE RESTRICT;

ALTER TABLE "ControlAcceso" ADD CONSTRAINT "FK_ControlAcceso_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario") ON DELETE RESTRICT;

ALTER TABLE "Estudiante" ADD CONSTRAINT "FK_Estudiante_Carrera_CarreraId" FOREIGN KEY ("CarreraId") REFERENCES "Carrera" ("IdCarrera");

ALTER TABLE "Estudiante" ADD CONSTRAINT "FK_Estudiante_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "Inscripcion" ADD CONSTRAINT "FK_Inscripcion_Periodo_PeriodoId" FOREIGN KEY ("PeriodoId") REFERENCES "Periodo" ("IdPeriodo");

ALTER TABLE "Mensaje" ADD CONSTRAINT "FK_Mensaje_Asignatura_AsignaturaId" FOREIGN KEY ("AsignaturaId") REFERENCES "Asignatura" ("IdAsignatura") ON DELETE RESTRICT;

ALTER TABLE "Mensaje" ADD CONSTRAINT "FK_Mensaje_Usuario_ReceptorUsuarioId" FOREIGN KEY ("ReceptorUsuarioId") REFERENCES "Usuario" ("IdUsuario");

ALTER TABLE "Mensaje" ADD CONSTRAINT "FK_Mensaje_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario") ON DELETE RESTRICT;

ALTER TABLE "Notificacion" ADD CONSTRAINT "FK_Notificacion_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario") ON DELETE RESTRICT;

ALTER TABLE "Profesor" ADD CONSTRAINT "FK_Profesor_Usuario_UsuarioId" FOREIGN KEY ("UsuarioId") REFERENCES "Usuario" ("IdUsuario");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260528040636_Fase2_Completa', '9.0.10');

COMMIT;

